### PR TITLE
Fix type of PaginatePipe to inherit the current collection type

### PR DESCRIPTION
**Pull request by johnfrades**
Changed the PaginationPipe transform type from any to be a generic type, so it can inherit the collections type and still be able to have type on HTML

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks for the PR!

Looks like the signature I suggested is not quite right though, see the [travis logs](https://travis-ci.org/michaelbromley/ngx-pagination/builds/544070542#L1197) - there is a TS error on line 43. 

Looks like solving this in a properly type-safe way will require a little more work. If you are interested in seeing this PR through to completion, I can give you some hints on how I would solve it. Otherwise I can  do it mysql. It is totally up to you.

**Comment by johnfrades** [comment]
Hmm i quite dont know how to approach this hehe

**Comment by michaelbromley** [comment]
Ok, that's no problem. I just didn't want to "steal your PR" without giving you the chance to get it merged. 😁 Totally understand if it's a bit beyond what you are ready to tackle.

Now that I've got the project open in my IDE I'll make the changes and publish a new version shortly. Also gives me a good opportunity to do some needed house-keeping on the repo 👍

**Comment by johnfrades** [comment]
hehe thanks man, probably i'll wait on your new code once you're done so i can see it ;)

**Comment by johnfrades** [comment]
awesome library by the way

**Pull request closed without merging**
